paths:
  lmstudio_bin_rel: ".lmstudio/bin"
  openjdk_bin_darwin: "/opt/homebrew/opt/openjdk/bin"

git:
  credential_helpers:
    darwin: osxkeychain
    linux: store

bitwarden:
  items:
    github_pat: "github.com PAT"

hosts:
  Seans-MacBook-Pro:
    enable_lmstudio: true
    enable_orbstack: true
